version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - APP_PORT=${APP_PORT}
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 